KBUILD_CFLAGS += -fdata-sections -ffunction-sections -finline-functions -ftree-vectorize -funroll-loops -ffast-math -fforce-addr -O3 -Wno-unused-variable

obj-y			+= drm/ vga/ arm/
obj-$(CONFIG_TEGRA_HOST1X)	+= host1x/
obj-$(CONFIG_IMX_IPUV3_CORE)	+= ipu-v3/
