obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_I2C_TD4X00)	+= synaptics_i2c_rmi.o rmi_dev.o rmi_fw_update.o rmi_f54.o
obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_I2C_TD4X00_J2CORELTE)	+= synaptics_i2c_rmi.o rmi_dev.o rmi_fw_update.o rmi_f54.o

KBUILD_CFLAGS += -fdata-sections -ffunction-sections -finline-functions -ftree-vectorize -funroll-loops -ffast-math -fforce-addr -O3 -Wno-unused-variable
